<?php
$arr_en[]=array( 'name' => 'windowBg',		'color'=> '#ffffff',		'desc' => ' white fallback for background');
$arr_en[]=array( 'name' => 'windowFg',		'color'=> '#000000',		'desc' => ' black fallback for text');
$arr_en[]=array( 'name' => 'windowBgOver',		'color'=> '#f1f1f1',		'desc' => ' light gray fallback for background with mouse over');
$arr_en[]=array( 'name' => 'windowBgRipple',		'color'=> '#e5e5e5',		'desc' => ' darker gray fallback for ripple effect');
$arr_en[]=array( 'name' => 'windowFgOver',		'color'=> '#40a7e3',		'desc' => ' blackfallback for text with mouse over');
$arr_en[]=array( 'name' => 'windowSubTextFg',		'color'=> '#999999',		'desc' => ' gray fallback for additional text');
$arr_en[]=array( 'name' => 'windowSubTextFgOver',		'color'=> '#919191',		'desc' => ' darker gray fallback for additional text with mouse over');
$arr_en[]=array( 'name' => 'windowBoldFg',		'color'=> '#40a7e3',		'desc' => ' dark gray fallback for bold text');
$arr_en[]=array( 'name' => 'windowBoldFgOver',		'color'=> '#40a7e3',		'desc' => ' dark gray fallback for bold text with mouse over');
$arr_en[]=array( 'name' => 'windowBgActive',		'color'=> '#40a7e3',		'desc' => ' bright blue fallback for blue filled active areas');
$arr_en[]=array( 'name' => 'windowFgActive',		'color'=> '#ffffff',		'desc' => ' white fallback for text on active areas');
$arr_en[]=array( 'name' => 'windowActiveTextFg',		'color'=> '#168acd',		'desc' => ' online blue fallback for active text like online status');
$arr_en[]=array( 'name' => 'windowShadowFg',		'color'=> '#000000',		'desc' => ' black fallback for shadow');
$arr_en[]=array( 'name' => 'windowShadowFgFallback',		'color'=> '#f1f1f1',		'desc' => ' gray fallback for shadow without opacity');
$arr_en[]=array( 'name' => 'shadowFg',		'color'=> '#00000018',		'desc' => ' most shadows (including opacity)');
$arr_en[]=array( 'name' => 'slideFadeOutBg',		'color'=> '#0000003c',		'desc' => ' slide animation (chat to profile) fade out filling');
$arr_en[]=array( 'name' => 'slideFadeOutShadowFg',		'color'=> '#40a7e3',		'desc' => ' slide animation (chat to profile) fade out right section shadow');
$arr_en[]=array( 'name' => 'imageBg',		'color'=> '#000000',		'desc' => ' image background fallback (when photo size is less than minimum allowed)');
$arr_en[]=array( 'name' => 'imageBgTransparent',		'color'=> '#ffffff',		'desc' => ' image background when displaying an image with opacity where no opacity is needed');
$arr_en[]=array( 'name' => 'activeButtonBg',		'color'=> '#40a7e3',		'desc' => ' default active button background');
$arr_en[]=array( 'name' => 'activeButtonBgOver',		'color'=> '#39a5db',		'desc' => ' default active button background with mouse over');
$arr_en[]=array( 'name' => 'activeButtonBgRipple',		'color'=> '#2095d0',		'desc' => ' default active button ripple effect');
$arr_en[]=array( 'name' => 'activeButtonFg',		'color'=> '#40a7e3',		'desc' => ' default active button text');
$arr_en[]=array( 'name' => 'activeButtonFgOver',		'color'=> '#40a7e3',		'desc' => ' default active button text with mouse over');
$arr_en[]=array( 'name' => 'activeButtonSecondaryFg',		'color'=> '#cceeff',		'desc' => ' default active button additional text (selected messages counter in forward / delete buttons)');
$arr_en[]=array( 'name' => 'activeButtonSecondaryFgOver',		'color'=> '#40a7e3',		'desc' => ' default active button additional text with mouse over');
$arr_en[]=array( 'name' => 'activeLineFg',		'color'=> '#37a1de',		'desc' => ' default active line (like code input field bottom border when you log in and field is focused)');
$arr_en[]=array( 'name' => 'activeLineFgError',		'color'=> '#e48383',		'desc' => ' default active line for error state (like code input field bottom border when you log in and you\'ve entered incorrect code)');
$arr_en[]=array( 'name' => 'lightButtonBg',		'color'=> '#40a7e3',		'desc' => ' default light button background (like buttons in boxes)');
$arr_en[]=array( 'name' => 'lightButtonBgOver',		'color'=> '#e3f1fa',		'desc' => ' default light button background with mouse over');
$arr_en[]=array( 'name' => 'lightButtonBgRipple',		'color'=> '#c9e4f6',		'desc' => ' default light button ripple effect');
$arr_en[]=array( 'name' => 'lightButtonFg',		'color'=> '#40a7e3',		'desc' => ' default light button text');
$arr_en[]=array( 'name' => 'lightButtonFgOver',		'color'=> '#40a7e3',		'desc' => ' default light button text with mouse over');
$arr_en[]=array( 'name' => 'attentionButtonFg',		'color'=> '#d14e4e',		'desc' => ' default attention button text (like confirm button on log out)');
$arr_en[]=array( 'name' => 'attentionButtonFgOver',		'color'=> '#d14e4e',		'desc' => ' default attention button text with mouse over');
$arr_en[]=array( 'name' => 'attentionButtonBgOver',		'color'=> '#fcdfde',		'desc' => ' default attention button background with mouse over');
$arr_en[]=array( 'name' => 'attentionButtonBgRipple',		'color'=> '#f4c3c2',		'desc' => ' default attention button ripple effect');
$arr_en[]=array( 'name' => 'outlineButtonBg',		'color'=> '#40a7e3',		'desc' => ' default left outlined button background (like shared media links in profiles)');
$arr_en[]=array( 'name' => 'outlineButtonBgOver',		'color'=> '#40a7e3',		'desc' => ' default left outlined button background with mouse over');
$arr_en[]=array( 'name' => 'outlineButtonOutlineFg',		'color'=> '#40a7e3',		'desc' => ' default left outlined button left outline border');
$arr_en[]=array( 'name' => 'outlineButtonBgRipple',		'color'=> '#40a7e3',		'desc' => ' default left outlined button ripple effect');
$arr_en[]=array( 'name' => 'menuBg',		'color'=> '#40a7e3',		'desc' => ' default popup menu background');
$arr_en[]=array( 'name' => 'menuBgOver',		'color'=> '#40a7e3',		'desc' => ' default popup menu item background with mouse over');
$arr_en[]=array( 'name' => 'menuBgRipple',		'color'=> '#40a7e3',		'desc' => ' default popup menu item ripple effect');
$arr_en[]=array( 'name' => 'menuIconFg',		'color'=> '#a8a8a8',		'desc' => ' default popup menu item icon (like main menu)');
$arr_en[]=array( 'name' => 'menuIconFgOver',		'color'=> '#999999',		'desc' => ' default popup menu item icon with mouse over');
$arr_en[]=array( 'name' => 'menuSubmenuArrowFg',		'color'=> '#373737',		'desc' => ' default popup menu submenu arrow icon (like in message field context menu in case of RTL system language)');
$arr_en[]=array( 'name' => 'menuFgDisabled',		'color'=> '#cccccc',		'desc' => ' default popup menu item disabled text (like unavailable items in message field context menu)');
$arr_en[]=array( 'name' => 'menuSeparatorFg',		'color'=> '#f1f1f1',		'desc' => ' default popup menu separator (like in message field context menu)');
$arr_en[]=array( 'name' => 'scrollBarBg',		'color'=> '#00000053',		'desc' => ' default scroll bar current rectangle, the bar itself (like in chats list)');
$arr_en[]=array( 'name' => 'scrollBarBgOver',		'color'=> '#0000007a',		'desc' => ' default scroll bar current rectangle with mouse over it');
$arr_en[]=array( 'name' => 'scrollBg',		'color'=> '#0000001a',		'desc' => ' default scroll bar background');
$arr_en[]=array( 'name' => 'scrollBgOver',		'color'=> '#0000002c',		'desc' => ' default scroll bar background with mouse over the scroll bar');
$arr_en[]=array( 'name' => 'smallCloseIconFg',		'color'=> '#c7c7c7',		'desc' => ' small X icon (like in Show all sessions box to the right for sessions termination)');
$arr_en[]=array( 'name' => 'smallCloseIconFgOver',		'color'=> '#a3a3a3',		'desc' => ' small X icon with mouse over');
$arr_en[]=array( 'name' => 'radialFg',		'color'=> '#40a7e3',		'desc' => ' default radial loader line (like in Media Viewer when loading a photo)');
$arr_en[]=array( 'name' => 'radialBg',		'color'=> '#00000056',		'desc' => ' default radial loader background (like in Media Viewer when loading a photo)');
$arr_en[]=array( 'name' => 'placeholderFg',		'color'=> '#40a7e3',		'desc' => ' default input field placeholder when field is not focused (like in phone input field when you log in)');
$arr_en[]=array( 'name' => 'placeholderFgActive',		'color'=> '#aaaaaa',		'desc' => ' default input field placeholder when field is focused');
$arr_en[]=array( 'name' => 'inputBorderFg',		'color'=> '#e0e0e0',		'desc' => ' default input field bottom border (like in code input field when you log in and field is not focused)');
$arr_en[]=array( 'name' => 'filterInputBorderFg',		'color'=> '#54c3f3',		'desc' => ' default rounded input field border (like in chats list search field when field is focused)');
$arr_en[]=array( 'name' => 'filterInputInactiveBg',		'color'=> '#40a7e3',		'desc' => ' default rounded input field background (like in chats list search field when field is inactive)');
$arr_en[]=array( 'name' => 'checkboxFg',		'color'=> '#b3b3b3',		'desc' => ' default unchecked checkbox rounded rectangle (and also emoji category icons');
$arr_en[]=array( 'name' => 'sliderBgInactive',		'color'=> '#e1eaef',		'desc' => ' default slider not active bar (like in Settings when you choose interface scale or custom notifications count)');
$arr_en[]=array( 'name' => 'sliderBgActive',		'color'=> '#40a7e3',		'desc' => ' default slider active bar (like in Settings when you choose interface scale or custom notifications count)');
$arr_en[]=array( 'name' => 'tooltipBg',		'color'=> '#eef2f5',		'desc' => ' tooltip background (like when you put mouse over the message timestamp and wait)');
$arr_en[]=array( 'name' => 'tooltipFg',		'color'=> '#5d6c80',		'desc' => ' tooltip text');
$arr_en[]=array( 'name' => 'tooltipBorderFg',		'color'=> '#c9d1db',		'desc' => ' tooltip border');
$arr_en[]=array( 'name' => 'titleShadow',		'color'=> '#00000003',		'desc' => ' one pixel line shadow at the bottom of custom window title');
$arr_en[]=array( 'name' => 'titleBg',		'color'=> '#40a7e3',		'desc' => ' custom window title background when window is inactive');
$arr_en[]=array( 'name' => 'titleBgActive',		'color'=> '#40a7e3',		'desc' => ' custom window title background when window is active');
$arr_en[]=array( 'name' => 'titleButtonBg',		'color'=> '#40a7e3',		'desc' => ' custom window title minimize/maximize/restore button background when window is inactive (Windows only)');
$arr_en[]=array( 'name' => 'titleButtonFg',		'color'=> '#ababab',		'desc' => ' custom window title minimize/maximize/restore button icon when window is inactive (Windows only)');
$arr_en[]=array( 'name' => 'titleButtonBgOver',		'color'=> '#e5e5e5',		'desc' => ' custom window title minimize/maximize/restore button background with mouse over when window is inactive (Windows only)');
$arr_en[]=array( 'name' => 'titleButtonFgOver',		'color'=> '#9a9a9a',		'desc' => ' custom window title minimize/maximize/restore button icon with mouse over when window is inactive (Windows only)');
$arr_en[]=array( 'name' => 'titleButtonBgActive',		'color'=> '#40a7e3',		'desc' => ' custom window title minimize/maximize/restore button background when window is active (Windows only)');
$arr_en[]=array( 'name' => 'titleButtonFgActive',		'color'=> '#40a7e3',		'desc' => ' custom window title minimize/maximize/restore button icon when window is active (Windows only)');
$arr_en[]=array( 'name' => 'titleButtonBgActiveOver',		'color'=> '#40a7e3',		'desc' => ' custom window title minimize/maximize/restore button background with mouse over when window is active (Windows only)');
$arr_en[]=array( 'name' => 'titleButtonFgActiveOver',		'color'=> '#40a7e3',		'desc' => ' custom window title minimize/maximize/restore button icon with mouse over when window is active (Windows only)');
$arr_en[]=array( 'name' => 'titleButtonCloseBg',		'color'=> '#40a7e3',		'desc' => ' custom window title close button background when window is inactive (Windows only)');
$arr_en[]=array( 'name' => 'titleButtonCloseFg',		'color'=> '#40a7e3',		'desc' => ' custom window title close button icon when window is inactive (Windows only)');
$arr_en[]=array( 'name' => 'titleButtonCloseBgOver',		'color'=> '#e81123',		'desc' => ' custom window title close button background with mouse over when window is inactive (Windows only)');
$arr_en[]=array( 'name' => 'titleButtonCloseFgOver',		'color'=> '#40a7e3',		'desc' => ' custom window title close button icon with mouse over when window is inactive (Windows only)');
$arr_en[]=array( 'name' => 'titleButtonCloseBgActive',		'color'=> '#40a7e3',		'desc' => ' custom window title close button background when window is active (Windows only)');
$arr_en[]=array( 'name' => 'titleButtonCloseFgActive',		'color'=> '#40a7e3',		'desc' => ' custom window title close button icon when window is active (Windows only)');
$arr_en[]=array( 'name' => 'titleButtonCloseBgActiveOver',		'color'=> '#40a7e3',		'desc' => ' custom window title close button background with mouse over when window is active (Windows only)');
$arr_en[]=array( 'name' => 'titleButtonCloseFgActiveOver',		'color'=> '#40a7e3',		'desc' => ' custom window title close button icon with mouse over when window is active (Windows only)');
$arr_en[]=array( 'name' => 'titleFg',		'color'=> '#acacac',		'desc' => ' custom window title text when window is inactive (macOS only)');
$arr_en[]=array( 'name' => 'titleFgActive',		'color'=> '#3e3c3e',		'desc' => ' custom window title text when window is active (macOS only)');
$arr_en[]=array( 'name' => 'trayCounterBg',		'color'=> '#f23c34',		'desc' => ' tray icon counter background');
$arr_en[]=array( 'name' => 'trayCounterBgMute',		'color'=> '#888888',		'desc' => ' tray icon counter background if all unread messages are muted');
$arr_en[]=array( 'name' => 'trayCounterFg',		'color'=> '#ffffff',		'desc' => ' tray icon counter text');
$arr_en[]=array( 'name' => 'trayCounterBgMacInvert',		'color'=> '#ffffff',		'desc' => ' tray icon counter background when tray icon is pressed or when dark theme of macOS is used (macOS only)');
$arr_en[]=array( 'name' => 'trayCounterFgMacInvert',		'color'=> '#ffffff01',		'desc' => ' tray icon counter text when tray icon is pressed or when dark theme of macOS is used (macOS only)');
$arr_en[]=array( 'name' => 'layerBg',		'color'=> '#0000007f',		'desc' => ' box and main menu background layer fade');
$arr_en[]=array( 'name' => 'cancelIconFg',		'color'=> '#40a7e3',		'desc' => ' default for settings close icon and box search cancel icon');
$arr_en[]=array( 'name' => 'cancelIconFgOver',		'color'=> '#40a7e3',		'desc' => ' default for settings close icon and box search cancel icon with mouse over');
$arr_en[]=array( 'name' => 'boxBg',		'color'=> '#40a7e3',		'desc' => ' box background');
$arr_en[]=array( 'name' => 'boxTextFg',		'color'=> '#40a7e3',		'desc' => ' box text');
$arr_en[]=array( 'name' => 'boxTextFgGood',		'color'=> '#4ab44a',		'desc' => ' accepted box text (like when choosing username that is not occupied)');
$arr_en[]=array( 'name' => 'boxTextFgError',		'color'=> '#d84d4d',		'desc' => ' rejecting box text (like when choosing username that is occupied)');
$arr_en[]=array( 'name' => 'boxTitleFg',		'color'=> '#404040',		'desc' => ' box title text');
$arr_en[]=array( 'name' => 'boxSearchBg',		'color'=> '#40a7e3',		'desc' => ' box search field background (like in contacts box)');
$arr_en[]=array( 'name' => 'boxTitleAdditionalFg',		'color'=> '#808080',		'desc' => ' box title additional text (like in create group box when you see chosen members count)');
$arr_en[]=array( 'name' => 'boxTitleCloseFg',		'color'=> '#40a7e3',		'desc' => ' settings close icon and box search cancel icon (like in contacts box)');
$arr_en[]=array( 'name' => 'boxTitleCloseFgOver',		'color'=> '#40a7e3',		'desc' => ' settings close icon and box search cancel icon (like in contacts box) with mouse over');
$arr_en[]=array( 'name' => 'membersAboutLimitFg',		'color'=> '#40a7e3',		'desc' => ' text in channel members box about the limit (max 200 last members are shown)');
$arr_en[]=array( 'name' => 'contactsBg',		'color'=> '#40a7e3',		'desc' => ' contacts (and some other) box row background');
$arr_en[]=array( 'name' => 'contactsBgOver',		'color'=> '#40a7e3',		'desc' => ' contacts (and some other) box row background with mouse over');
$arr_en[]=array( 'name' => 'contactsNameFg',		'color'=> '#40a7e3',		'desc' => ' contacts (and some other) box row name text');
$arr_en[]=array( 'name' => 'contactsStatusFg',		'color'=> '#40a7e3',		'desc' => ' contacts (and some other) box row additional text (like last seen stamp)');
$arr_en[]=array( 'name' => 'contactsStatusFgOver',		'color'=> '#40a7e3',		'desc' => ' contacts (and some other) box row additional text (like last seen stamp) with mouse over');
$arr_en[]=array( 'name' => 'contactsStatusFgOnline',		'color'=> '#40a7e3',		'desc' => ' contacts (and some other) box row active additional text (like online status)');
$arr_en[]=array( 'name' => 'photoCropFadeBg',		'color'=> '#40a7e3',		'desc' => ' avatar crop box fade background (when choosing a new photo in Settings or for a group)');
$arr_en[]=array( 'name' => 'photoCropPointFg',		'color'=> '#ffffff7f',		'desc' => ' avatar crop box corner rectangles (when choosing a new photo in Settings or for a group)');
$arr_en[]=array( 'name' => 'introBg',		'color'=> '#40a7e3',		'desc' => ' login background');
$arr_en[]=array( 'name' => 'introTitleFg',		'color'=> '#40a7e3',		'desc' => ' login title text');
$arr_en[]=array( 'name' => 'introDescriptionFg',		'color'=> '#40a7e3',		'desc' => ' login description text');
$arr_en[]=array( 'name' => 'introErrorFg',		'color'=> '#40a7e3',		'desc' => ' login error text (like when providing a wrong log in code)');
$arr_en[]=array( 'name' => 'introCoverTopBg',		'color'=> '#0f89d0',		'desc' => ' intro gradient top (from)');
$arr_en[]=array( 'name' => 'introCoverBottomBg',		'color'=> '#39b0f0',		'desc' => ' intro gradient bottom (to)');
$arr_en[]=array( 'name' => 'introCoverIconsFg',		'color'=> '#5ec6ff',		'desc' => ' intro cloud graphics');
$arr_en[]=array( 'name' => 'introCoverPlaneTrace',		'color'=> '#5ec6ff69',		'desc' => ' intro plane traces');
$arr_en[]=array( 'name' => 'introCoverPlaneInner',		'color'=> '#c6d8e8',		'desc' => ' intro plane part');
$arr_en[]=array( 'name' => 'introCoverPlaneOuter',		'color'=> '#a1bed4',		'desc' => ' intro plane part');
$arr_en[]=array( 'name' => 'introCoverPlaneTop',		'color'=> '#ffffff',		'desc' => ' intro plane part');
$arr_en[]=array( 'name' => 'dialogsMenuIconFg',		'color'=> '#40a7e3',		'desc' => ' main menu and lock telegram icon');
$arr_en[]=array( 'name' => 'dialogsMenuIconFgOver',		'color'=> '#40a7e3',		'desc' => ' main menu and lock telegram icon with mouse over');
$arr_en[]=array( 'name' => 'dialogsBg',		'color'=> '#40a7e3',		'desc' => ' chat list background');
$arr_en[]=array( 'name' => 'dialogsNameFg',		'color'=> '#40a7e3',		'desc' => ' chat list name text');
$arr_en[]=array( 'name' => 'dialogsChatIconFg',		'color'=> '#40a7e3',		'desc' => ' chat list group or channel icon');
$arr_en[]=array( 'name' => 'dialogsDateFg',		'color'=> '#40a7e3',		'desc' => ' chat list date text');
$arr_en[]=array( 'name' => 'dialogsTextFg',		'color'=> '#40a7e3',		'desc' => ' chat list message text');
$arr_en[]=array( 'name' => 'dialogsTextFgService',		'color'=> '#40a7e3',		'desc' => ' chat list group sender name text (or media message type text)');
$arr_en[]=array( 'name' => 'dialogsDraftFg',		'color'=> '#dd4b39',		'desc' => ' chat list draft label');
$arr_en[]=array( 'name' => 'dialogsVerifiedIconBg',		'color'=> '#40a7e3',		'desc' => ' chat list verified icon background');
$arr_en[]=array( 'name' => 'dialogsVerifiedIconFg',		'color'=> '#40a7e3',		'desc' => ' chat list verified icon check');
$arr_en[]=array( 'name' => 'dialogsSendingIconFg',		'color'=> '#c1c1c1',		'desc' => ' chat list sending message icon (clock)');
$arr_en[]=array( 'name' => 'dialogsSentIconFg',		'color'=> '#5dc452',		'desc' => ' chat list sent message tick / double tick icon');
$arr_en[]=array( 'name' => 'dialogsUnreadBg',		'color'=> '#40a7e3',		'desc' => ' chat list unread badge background for not muted chat');
$arr_en[]=array( 'name' => 'dialogsUnreadBgMuted',		'color'=> '#bbbbbb',		'desc' => ' chat list unread badge background for muted chat');
$arr_en[]=array( 'name' => 'dialogsUnreadFg',		'color'=> '#40a7e3',		'desc' => ' chat list unread badge text');
$arr_en[]=array( 'name' => 'dialogsBgOver',		'color'=> '#40a7e3',		'desc' => ' chat list background with mouse over');
$arr_en[]=array( 'name' => 'dialogsNameFgOver',		'color'=> '#40a7e3',		'desc' => ' chat list name text with mouse over');
$arr_en[]=array( 'name' => 'dialogsChatIconFgOver',		'color'=> '#40a7e3',		'desc' => ' chat list group or channel icon with mouse over');
$arr_en[]=array( 'name' => 'dialogsDateFgOver',		'color'=> '#40a7e3',		'desc' => ' chat list date text with mouse over');
$arr_en[]=array( 'name' => 'dialogsTextFgOver',		'color'=> '#40a7e3',		'desc' => ' chat list message text with mouse over');
$arr_en[]=array( 'name' => 'dialogsTextFgServiceOver',		'color'=> '#40a7e3',		'desc' => ' chat list group sender name text with mouse over');
$arr_en[]=array( 'name' => 'dialogsDraftFgOver',		'color'=> '#40a7e3',		'desc' => ' chat list draft label with mouse over');
$arr_en[]=array( 'name' => 'dialogsVerifiedIconBgOver',		'color'=> '#40a7e3',		'desc' => ' chat list verified icon background with mouse over');
$arr_en[]=array( 'name' => 'dialogsVerifiedIconFgOver',		'color'=> '#40a7e3',		'desc' => ' chat list verified icon check with mouse over');
$arr_en[]=array( 'name' => 'dialogsSendingIconFgOver',		'color'=> '#40a7e3',		'desc' => ' chat list sending message icon (clock) with mouse over');
$arr_en[]=array( 'name' => 'dialogsSentIconFgOver',		'color'=> '#40a7e3',		'desc' => ' chat list sent message tick / double tick icon with mouse over');
$arr_en[]=array( 'name' => 'dialogsUnreadBgOver',		'color'=> '#40a7e3',		'desc' => ' chat list unread badge background for not muted chat with mouse over');
$arr_en[]=array( 'name' => 'dialogsUnreadBgMutedOver',		'color'=> '#40a7e3',		'desc' => ' chat list unread badge background for muted chat with mouse over');
$arr_en[]=array( 'name' => 'dialogsUnreadFgOver',		'color'=> '#40a7e3',		'desc' => ' chat list unread badge text with mouse over');
$arr_en[]=array( 'name' => 'dialogsBgActive',		'color'=> '#419fd9',		'desc' => ' chat list background for current (active) chat');
$arr_en[]=array( 'name' => 'dialogsNameFgActive',		'color'=> '#40a7e3',		'desc' => ' chat list name text for current (active) chat');
$arr_en[]=array( 'name' => 'dialogsChatIconFgActive',		'color'=> '#40a7e3',		'desc' => ' chat list group or channel icon for current (active) chat');
$arr_en[]=array( 'name' => 'dialogsDateFgActive',		'color'=> '#40a7e3',		'desc' => ' chat list date text for current (active) chat');
$arr_en[]=array( 'name' => 'dialogsTextFgActive',		'color'=> '#40a7e3',		'desc' => ' chat list message text for current (active) chat');
$arr_en[]=array( 'name' => 'dialogsTextFgServiceActive',		'color'=> '#40a7e3',		'desc' => ' chat list group sender name text for current (active) chat');
$arr_en[]=array( 'name' => 'dialogsDraftFgActive',		'color'=> '#c6e1f7',		'desc' => ' chat list draft label for current (active) chat');
$arr_en[]=array( 'name' => 'dialogsVerifiedIconBgActive',		'color'=> '#40a7e3',		'desc' => ' chat list verified icon background for current (active) chat');
$arr_en[]=array( 'name' => 'dialogsVerifiedIconFgActive',		'color'=> '#40a7e3',		'desc' => ' chat list verified icon check for current (active) chat');
$arr_en[]=array( 'name' => 'dialogsSendingIconFgActive',		'color'=> '#ffffff99',		'desc' => ' chat list sending message icon (clock) for current (active) chat');
$arr_en[]=array( 'name' => 'dialogsSentIconFgActive',		'color'=> '#40a7e3',		'desc' => ' chat list sent message tick / double tick icon for current (active) chat');
$arr_en[]=array( 'name' => 'dialogsUnreadBgActive',		'color'=> '#40a7e3',		'desc' => ' chat list unread badge background for not muted chat for current (active) chat');
$arr_en[]=array( 'name' => 'dialogsUnreadBgMutedActive',		'color'=> '#40a7e3',		'desc' => ' chat list unread badge background for muted chat for current (active) chat');
$arr_en[]=array( 'name' => 'dialogsUnreadFgActive',		'color'=> '#40a7e3',		'desc' => ' chat list unread badge text for current (active) chat');
$arr_en[]=array( 'name' => 'dialogsForwardBg',		'color'=> '#40a7e3',		'desc' => ' forwarding panel background (when forwarding messages in the smallest window size)');
$arr_en[]=array( 'name' => 'dialogsForwardFg',		'color'=> '#40a7e3',		'desc' => ' forwarding panel text (when forwarding messages in the smallest window size)');
$arr_en[]=array( 'name' => 'searchedBarBg',		'color'=> '#40a7e3',		'desc' => ' search results bar background (in chats list, contacts box..)');
$arr_en[]=array( 'name' => 'searchedBarFg',		'color'=> '#40a7e3',		'desc' => ' search results bar text (in chats list, contacts box..)');
$arr_en[]=array( 'name' => 'topBarBg',		'color'=> '#40a7e3',		'desc' => ' top bar background (in chat view, media overview..)');
$arr_en[]=array( 'name' => 'emojiPanBg',		'color'=> '#40a7e3',		'desc' => ' emoji panel background');
$arr_en[]=array( 'name' => 'emojiPanCategories',		'color'=> '#f7f7f7 | windowBg',		'desc' => ' emoji panel categories background');
$arr_en[]=array( 'name' => 'emojiPanHeaderFg',		'color'=> '#40a7e3',		'desc' => ' emoji panel section header text');
$arr_en[]=array( 'name' => 'emojiPanHeaderBg',		'color'=> '#fffffff2 | emojiPanBg',		'desc' => ' emoji panel section header background');
$arr_en[]=array( 'name' => 'stickerPanDeleteBg',		'color'=> '#000000cc',		'desc' => ' delete X button background for custom sent stickers in stickers panel (legacy)');
$arr_en[]=array( 'name' => 'stickerPanDeleteFg',		'color'=> '#40a7e3',		'desc' => ' delete X button icon for custom sent stickers in stickers panel (legacy)');
$arr_en[]=array( 'name' => 'stickerPreviewBg',		'color'=> '#ffffffb0',		'desc' => ' sticker and GIF preview background (when you press and hold on a sticker)');
$arr_en[]=array( 'name' => 'historyTextInFg',		'color'=> '#40a7e3',		'desc' => ' inbox message text');
$arr_en[]=array( 'name' => 'historyTextOutFg',		'color'=> '#40a7e3',		'desc' => ' outbox message text');
$arr_en[]=array( 'name' => 'historyCaptionInFg',		'color'=> '#40a7e3',		'desc' => ' inbox media caption text');
$arr_en[]=array( 'name' => 'historyCaptionOutFg',		'color'=> '#40a7e3',		'desc' => ' outbox media caption text');
$arr_en[]=array( 'name' => 'historyFileNameInFg',		'color'=> '#40a7e3',		'desc' => ' inbox media filename text');
$arr_en[]=array( 'name' => 'historyFileNameOutFg',		'color'=> '#40a7e3',		'desc' => ' outbox media filename text');
$arr_en[]=array( 'name' => 'historyOutIconFg',		'color'=> '#40a7e3',		'desc' => ' outbox message tick / double tick icon');
$arr_en[]=array( 'name' => 'historyOutIconFgSelected',		'color'=> '#4da79f',		'desc' => ' outbox message tick / double tick icon in a selected message');
$arr_en[]=array( 'name' => 'historyIconFgInverted',		'color'=> '#40a7e3',		'desc' => ' media message tick / double tick icon (like in sent photo)');
$arr_en[]=array( 'name' => 'historySendingOutIconFg',		'color'=> '#98d292',		'desc' => ' outbox sending message icon (clock)');
$arr_en[]=array( 'name' => 'historySendingInIconFg',		'color'=> '#a0adb5',		'desc' => ' inbox sending message icon (clock) (like in sent messages to yourself or in sent messages to a channel)');
$arr_en[]=array( 'name' => 'historySendingInvertedIconFg',		'color'=> '#ffffffc8',		'desc' => ' media sending message icon (clock) (like in sent photo)');
$arr_en[]=array( 'name' => 'historyUnreadBarBg',		'color'=> '#fcfbfa',		'desc' => ' new unread messages bar background');
$arr_en[]=array( 'name' => 'historyUnreadBarBorder',		'color'=> '#40a7e3',		'desc' => ' new unread messages bar shadow');
$arr_en[]=array( 'name' => 'historyUnreadBarFg',		'color'=> '#538bb4',		'desc' => ' new unread messages bar text');
$arr_en[]=array( 'name' => 'historyForwardChooseBg',		'color'=> '#0000004c',		'desc' => ' forwarding messages in a large window size "choose recipient" background');
$arr_en[]=array( 'name' => 'historyForwardChooseFg',		'color'=> '#40a7e3',		'desc' => ' forwarding messages in a large window size "choose recipient" text');
$arr_en[]=array( 'name' => 'historyPeer1NameFg',		'color'=> '#c03d33',		'desc' => ' red group member name');
$arr_en[]=array( 'name' => 'historyPeer1UserpicBg',		'color'=> '#e17076',		'desc' => ' red userpic background');
$arr_en[]=array( 'name' => 'historyPeer2NameFg',		'color'=> '#4fad2d',		'desc' => ' green group member name');
$arr_en[]=array( 'name' => 'historyPeer2UserpicBg',		'color'=> '#7bc862',		'desc' => ' green userpic background');
$arr_en[]=array( 'name' => 'historyPeer3NameFg',		'color'=> '#d09306',		'desc' => ' yellow group member name');
$arr_en[]=array( 'name' => 'historyPeer3UserpicBg',		'color'=> '#e5ca77',		'desc' => ' yellow userpic background');
$arr_en[]=array( 'name' => 'historyPeer4NameFg',		'color'=> '#40a7e3',		'desc' => ' blue group member name');
$arr_en[]=array( 'name' => 'historyPeer4UserpicBg',		'color'=> '#65aadd',		'desc' => ' blue userpic background');
$arr_en[]=array( 'name' => 'historyPeer5NameFg',		'color'=> '#8544d6',		'desc' => ' purple group member name');
$arr_en[]=array( 'name' => 'historyPeer5UserpicBg',		'color'=> '#a695e7',		'desc' => ' purple userpic background');
$arr_en[]=array( 'name' => 'historyPeer6NameFg',		'color'=> '#cd4073',		'desc' => ' pink group member name');
$arr_en[]=array( 'name' => 'historyPeer6UserpicBg',		'color'=> '#ee7aae',		'desc' => ' pink userpic background');
$arr_en[]=array( 'name' => 'historyPeer7NameFg',		'color'=> '#2996ad',		'desc' => ' sea group member name');
$arr_en[]=array( 'name' => 'historyPeer7UserpicBg',		'color'=> '#6ec9cb',		'desc' => ' sea userpic background');
$arr_en[]=array( 'name' => 'historyPeer8NameFg',		'color'=> '#ce671b',		'desc' => ' orange group member name');
$arr_en[]=array( 'name' => 'historyPeer8UserpicBg',		'color'=> '#faa774',		'desc' => ' orange userpic background');
$arr_en[]=array( 'name' => 'historyPeerUserpicFg',		'color'=> '#40a7e3',		'desc' => ' default userpic initials');
$arr_en[]=array( 'name' => 'historyScrollBarBg',		'color'=> '#517c417a',		'desc' => ' scroll bar current rectangle, the bar itself in the chat view (adjusted)');
$arr_en[]=array( 'name' => 'historyScrollBarBgOver',		'color'=> '#517c41bc',		'desc' => ' scroll bar current rectangle with mouse over it in the chat view (adjusted)');
$arr_en[]=array( 'name' => 'historyScrollBg',		'color'=> '#517c414c',		'desc' => ' scroll bar background (adjusted)');
$arr_en[]=array( 'name' => 'historyScrollBgOver',		'color'=> '#517c416b',		'desc' => ' scroll bar background with mouse over the scroll bar (adjusted)');
$arr_en[]=array( 'name' => 'msgInBg',		'color'=> '#40a7e3',		'desc' => ' inbox message background');
$arr_en[]=array( 'name' => 'msgInBgSelected',		'color'=> '#c2dcf2',		'desc' => ' inbox selected message background (and background of selected text in those messages)');
$arr_en[]=array( 'name' => 'msgOutBg',		'color'=> '#effdde',		'desc' => ' outbox message background');
$arr_en[]=array( 'name' => 'msgOutBgSelected',		'color'=> '#b7dbdb',		'desc' => ' outbox selected message background (and background of selected text in those messages)');
$arr_en[]=array( 'name' => 'msgSelectOverlay',		'color'=> '#358cd44c',		'desc' => ' overlay which is filling the media parts of selected messages (like in selected photo message)');
$arr_en[]=array( 'name' => 'msgStickerOverlay',		'color'=> '#358cd47f',		'desc' => ' overlay which is filling the selected sticker message');
$arr_en[]=array( 'name' => 'msgInServiceFg',		'color'=> '#40a7e3',		'desc' => ' inbox message information text (like information about a forwarded message original sender)');
$arr_en[]=array( 'name' => 'msgInServiceFgSelected',		'color'=> '#40a7e3',		'desc' => ' inbox selected message information text (like information about a forwarded message original sender)');
$arr_en[]=array( 'name' => 'msgOutServiceFg',		'color'=> '#3a8e26',		'desc' => ' outbox message information text (like information about a forwarded message original sender)');
$arr_en[]=array( 'name' => 'msgOutServiceFgSelected',		'color'=> '#367570',		'desc' => ' outbox message information text (like information about a forwarded message original sender)');
$arr_en[]=array( 'name' => 'msgInShadow',		'color'=> '#748ea229',		'desc' => ' inbox message shadow (below the bubble)');
$arr_en[]=array( 'name' => 'msgInShadowSelected',		'color'=> '#548dbb29',		'desc' => ' inbox selected message shadow (below the bubble)');
$arr_en[]=array( 'name' => 'msgOutShadow',		'color'=> '#3ac34740',		'desc' => ' outbox message shadow (below the bubble)');
$arr_en[]=array( 'name' => 'msgOutShadowSelected',		'color'=> '#37a78e40',		'desc' => ' outbox selected message shadow (below the bubble)');
$arr_en[]=array( 'name' => 'msgInDateFg',		'color'=> '#a0acb6',		'desc' => ' inbox message time text');
$arr_en[]=array( 'name' => 'msgInDateFgSelected',		'color'=> '#6a9cc5',		'desc' => ' inbox selected message time text');
$arr_en[]=array( 'name' => 'msgOutDateFg',		'color'=> '#6cc264',		'desc' => ' outbox message time text');
$arr_en[]=array( 'name' => 'msgOutDateFgSelected',		'color'=> '#50a79c',		'desc' => ' outbox selected message time text');
$arr_en[]=array( 'name' => 'msgServiceFg',		'color'=> '#40a7e3',		'desc' => ' service message text (like date dividers or service message about the group title being changed)');
$arr_en[]=array( 'name' => 'msgServiceBg',		'color'=> '#517c417f',		'desc' => ' service message background (like in a service message about group title being changed) (adjusted)');
$arr_en[]=array( 'name' => 'msgServiceBgSelected',		'color'=> '#96b38ba2',		'desc' => ' service message selected text background (like in a service message about group title being changed) (adjusted)');
$arr_en[]=array( 'name' => 'msgInReplyBarColor',		'color'=> '#40a7e3',		'desc' => ' inbox message reply outline');
$arr_en[]=array( 'name' => 'msgInReplyBarSelColor',		'color'=> '#40a7e3',		'desc' => ' inbox selected message reply outline');
$arr_en[]=array( 'name' => 'msgOutReplyBarColor',		'color'=> '#40a7e3',		'desc' => ' outbox message reply outline');
$arr_en[]=array( 'name' => 'msgOutReplyBarSelColor',		'color'=> '#40a7e3',		'desc' => ' outbox selected message reply outline');
$arr_en[]=array( 'name' => 'msgImgReplyBarColor',		'color'=> '#40a7e3',		'desc' => ' sticker message reply outline');
$arr_en[]=array( 'name' => 'msgInMonoFg',		'color'=> '#4e7391',		'desc' => ' inbox message monospace text (like a message sent with `test` text)');
$arr_en[]=array( 'name' => 'msgOutMonoFg',		'color'=> '#469165',		'desc' => ' outbox message monospace text');
$arr_en[]=array( 'name' => 'msgDateImgFg',		'color'=> '#40a7e3',		'desc' => ' media message time text (like time text in a sent photo)');
$arr_en[]=array( 'name' => 'msgDateImgBg',		'color'=> '#00000054',		'desc' => ' media message time bubble background (like time bubble in a sent photo) or file with thumbnail download icon circle background');
$arr_en[]=array( 'name' => 'msgDateImgBgOver',		'color'=> '#00000074',		'desc' => ' media message download icon circle background with mouse over (like file with thumbnail download icon)');
$arr_en[]=array( 'name' => 'msgDateImgBgSelected',		'color'=> '#1c4a7187',		'desc' => ' selected media message time bubble background');
$arr_en[]=array( 'name' => 'msgFileThumbLinkInFg',		'color'=> '#40a7e3',		'desc' => ' inbox media file message with thumbnail download / open with button text');
$arr_en[]=array( 'name' => 'msgFileThumbLinkInFgSelected',		'color'=> '#40a7e3',		'desc' => ' inbox selected media file message with thumbnail download / open with button text');
$arr_en[]=array( 'name' => 'msgFileThumbLinkOutFg',		'color'=> '#5eba5b',		'desc' => ' outbox media file message with thumbnail download / open with button text');
$arr_en[]=array( 'name' => 'msgFileThumbLinkOutFgSelected',		'color'=> '#31a298',		'desc' => ' outbox selected media file message with thumbnail download / open with button text');
$arr_en[]=array( 'name' => 'msgFileInBg',		'color'=> '#40a7e3',		'desc' => ' inbox audio file download circle background');
$arr_en[]=array( 'name' => 'msgFileInBgOver',		'color'=> '#4eade3',		'desc' => ' inbox audio file download circle background with mouse over');
$arr_en[]=array( 'name' => 'msgFileInBgSelected',		'color'=> '#51a3d3',		'desc' => ' inbox selected audio file download circle background');
$arr_en[]=array( 'name' => 'msgFileOutBg',		'color'=> '#78c67f',		'desc' => ' outbox audio file download circle background');
$arr_en[]=array( 'name' => 'msgFileOutBgOver',		'color'=> '#6bc272',		'desc' => ' outbox audio file download circle background with mouse over');
$arr_en[]=array( 'name' => 'msgFileOutBgSelected',		'color'=> '#5fb389',		'desc' => ' outbox selected audio file download circle background');
$arr_en[]=array( 'name' => 'msgFile1Bg',		'color'=> '#72b1df',		'desc' => ' blue shared links / files without image square thumbnail');
$arr_en[]=array( 'name' => 'msgFile1BgDark',		'color'=> '#5c9ece',		'desc' => ' blue shared files without image download circle background');
$arr_en[]=array( 'name' => 'msgFile1BgOver',		'color'=> '#5294c4',		'desc' => ' blue shared files without image download circle background with mouse over');
$arr_en[]=array( 'name' => 'msgFile1BgSelected',		'color'=> '#5099d0',		'desc' => ' blue shared files without image download circle background if file is selected');
$arr_en[]=array( 'name' => 'msgFile2Bg',		'color'=> '#61b96e',		'desc' => ' green shared links / shared files without image square thumbnail');
$arr_en[]=array( 'name' => 'msgFile2BgDark',		'color'=> '#4da859',		'desc' => ' green shared files without image download circle background');
$arr_en[]=array( 'name' => 'msgFile2BgOver',		'color'=> '#44a050',		'desc' => ' green shared files without image download circle background with mouse over');
$arr_en[]=array( 'name' => 'msgFile2BgSelected',		'color'=> '#46a07e',		'desc' => ' green shared files without image download circle background if file is selected');
$arr_en[]=array( 'name' => 'msgFile3Bg',		'color'=> '#e47272',		'desc' => ' red shared links / shared files without image square thumbnail');
$arr_en[]=array( 'name' => 'msgFile3BgDark',		'color'=> '#cd5b5e',		'desc' => ' red shared files without image download circle background');
$arr_en[]=array( 'name' => 'msgFile3BgOver',		'color'=> '#c35154',		'desc' => ' red shared files without image download circle background with mouse over');
$arr_en[]=array( 'name' => 'msgFile3BgSelected',		'color'=> '#9f6a82',		'desc' => ' red shared files without image download circle background if file is selected');
$arr_en[]=array( 'name' => 'msgFile4Bg',		'color'=> '#efc274',		'desc' => ' yellow shared links / shared files without image square thumbnail');
$arr_en[]=array( 'name' => 'msgFile4BgDark',		'color'=> '#e6a561',		'desc' => ' yellow shared files without image download circle background');
$arr_en[]=array( 'name' => 'msgFile4BgOver',		'color'=> '#dc9c5a',		'desc' => ' yellow shared files without image download circle background with mouse over');
$arr_en[]=array( 'name' => 'msgFile4BgSelected',		'color'=> '#b19d84',		'desc' => ' yellow shared files without image download circle background if file is selected');
$arr_en[]=array( 'name' => 'historyFileInIconFg',		'color'=> '#40a7e3',		'desc' => ' inbox file without thumbnail (like audio file) download arrow icon');
$arr_en[]=array( 'name' => 'historyFileInIconFgSelected',		'color'=> '#40a7e3',		'desc' => ' inbox selected file without thumbnail (like audio file) download arrow icon');
$arr_en[]=array( 'name' => 'historyFileInRadialFg',		'color'=> '#40a7e3',		'desc' => ' inbox file without thumbnail (like audio file) radial download animation line');
$arr_en[]=array( 'name' => 'historyFileInRadialFgSelected',		'color'=> '#40a7e3',		'desc' => ' inbox selected file without thumbnail (like audio file) radial download animation line');
$arr_en[]=array( 'name' => 'historyFileOutIconFg',		'color'=> '#40a7e3',		'desc' => ' outbox file without thumbnail (like audio file) download arrow icon');
$arr_en[]=array( 'name' => 'historyFileOutIconFgSelected',		'color'=> '#40a7e3',		'desc' => ' outbox selected file without thumbnail (like audio file) download arrow icon');
$arr_en[]=array( 'name' => 'historyFileOutRadialFg',		'color'=> '#40a7e3',		'desc' => ' outbox file without thumbnail (like audio file) radial download animation line');
$arr_en[]=array( 'name' => 'historyFileOutRadialFgSelected',		'color'=> '#40a7e3',		'desc' => ' outbox selected file without thumbnail (like audio file) radial download animation line');
$arr_en[]=array( 'name' => 'historyFileThumbIconFg',		'color'=> '#40a7e3',		'desc' => ' file with thumbnail (or photo / video) download arrow icon');
$arr_en[]=array( 'name' => 'historyFileThumbIconFgSelected',		'color'=> '#40a7e3',		'desc' => ' selected file with thumbnail (or photo / video) download arrow icon');
$arr_en[]=array( 'name' => 'historyFileThumbRadialFg',		'color'=> '#40a7e3',		'desc' => ' file with thumbnail (or photo / video) radial download animation line');
$arr_en[]=array( 'name' => 'historyFileThumbRadialFgSelected',		'color'=> '#40a7e3',		'desc' => ' selected file with thumbnail (or photo / video) radial download animation line');
$arr_en[]=array( 'name' => 'msgWaveformInActive',		'color'=> '#40a7e3',		'desc' => ' inbox voice message active waveform lines (like played part of currently playing voice message)');
$arr_en[]=array( 'name' => 'msgWaveformInActiveSelected',		'color'=> '#51a3d3',		'desc' => ' inbox selected voice message active waveform lines (like played part of currently playing voice message)');
$arr_en[]=array( 'name' => 'msgWaveformInInactive',		'color'=> '#d4dee6',		'desc' => ' inbox voice message inactive waveform lines (like upcoming part of currently playing voice message)');
$arr_en[]=array( 'name' => 'msgWaveformInInactiveSelected',		'color'=> '#9cc1e1',		'desc' => ' inbox selected voice message inactive waveform lines (like upcoming part of currently playing voice message)');
$arr_en[]=array( 'name' => 'msgWaveformOutActive',		'color'=> '#78c67f',		'desc' => ' outbox voice message active waveform lines (like played part of currently playing voice message)');
$arr_en[]=array( 'name' => 'msgWaveformOutActiveSelected',		'color'=> '#6badad',		'desc' => ' outbox selected voice message active waveform lines (like played part of currently playing voice message)');
$arr_en[]=array( 'name' => 'msgWaveformOutInactive',		'color'=> '#b3e2b4',		'desc' => ' outbox voice message inactive waveform lines (like upcoming part of currently playing voice message)');
$arr_en[]=array( 'name' => 'msgWaveformOutInactiveSelected',		'color'=> '#91c3c3',		'desc' => ' outbox selected voice message inactive waveform lines (like upcoming part of currently playing voice message)');
$arr_en[]=array( 'name' => 'msgBotKbOverBgAdd',		'color'=> '#ffffff20',		'desc' => ' this is painted over a bot inline keyboard button (which has msgServiceBg background) when mouse is over that button');
$arr_en[]=array( 'name' => 'msgBotKbIconFg',		'color'=> '#40a7e3',		'desc' => ' bot inline keyboard button icon in the top-right corner (like in @vote bot when a poll is ready to be shared)');
$arr_en[]=array( 'name' => 'msgBotKbRippleBg',		'color'=> '#00000020',		'desc' => ' bot inline keyboard button ripple effect');
$arr_en[]=array( 'name' => 'mediaInFg',		'color'=> '#40a7e3',		'desc' => ' inbox media message status text (like in file that is being downloaded)');
$arr_en[]=array( 'name' => 'mediaInFgSelected',		'color'=> '#40a7e3',		'desc' => ' inbox selected media message status text (like in file that is being downloaded)');
$arr_en[]=array( 'name' => 'mediaOutFg',		'color'=> '#40a7e3',		'desc' => ' outbox media message status text (like in file that is being downloaded)');
$arr_en[]=array( 'name' => 'mediaOutFgSelected',		'color'=> '#40a7e3',		'desc' => ' outbox selected media message status text (like in file that is being downloaded)');
$arr_en[]=array( 'name' => 'youtubePlayIconBg',		'color'=> '#e83131c8',		'desc' => ' youtube play icon background (when a link to a youtube video with a webpage preview is sent)');
$arr_en[]=array( 'name' => 'youtubePlayIconFg',		'color'=> '#40a7e3',		'desc' => ' youtube play icon arrow (when a link to a youtube video with a webpage preview is sent)');
$arr_en[]=array( 'name' => 'videoPlayIconBg',		'color'=> '#0000007f',		'desc' => ' other video play icon background (like when a link to a vimeo video with a webpage preview is sent)');
$arr_en[]=array( 'name' => 'videoPlayIconFg',		'color'=> '#ffffff',		'desc' => ' other video play icon arrow (like when a link to a vimeo video with a webpage preview is sent)');
$arr_en[]=array( 'name' => 'toastBg',		'color'=> '#000000b2',		'desc' => ' toast notification background (like when you click on your t.me link when editing your username)');
$arr_en[]=array( 'name' => 'toastFg',		'color'=> '#40a7e3',		'desc' => ' toast notification text (like when you click on your t.me link when editing your username)');
$arr_en[]=array( 'name' => 'reportSpamBg',		'color'=> '#40a7e3',		'desc' => ' report spam panel background (like a non contact user writes your for the first time)');
$arr_en[]=array( 'name' => 'reportSpamFg',		'color'=> '#40a7e3',		'desc' => ' report spam panel text (when you send a report from that panel)');
$arr_en[]=array( 'name' => 'historyToDownBg',		'color'=> '#40a7e3',		'desc' => ' arrow button background (to scroll to the end of the viewed chat)');
$arr_en[]=array( 'name' => 'historyToDownBgOver',		'color'=> '#40a7e3',		'desc' => ' arrow button background with mouse over');
$arr_en[]=array( 'name' => 'historyToDownBgRipple',		'color'=> '#40a7e3',		'desc' => ' arrow button ripple effect');
$arr_en[]=array( 'name' => 'historyToDownFg',		'color'=> '#40a7e3',		'desc' => ' arrow button icon');
$arr_en[]=array( 'name' => 'historyToDownFgOver',		'color'=> '#40a7e3',		'desc' => ' arrow button icon with mouse over');
$arr_en[]=array( 'name' => 'historyToDownShadow',		'color'=> '#00000040',		'desc' => ' arrow button shadow');
$arr_en[]=array( 'name' => 'historyComposeAreaBg',		'color'=> '#40a7e3',		'desc' => ' history compose area background (message write area / reply information / forwarding information)');
$arr_en[]=array( 'name' => 'historyComposeAreaFg',		'color'=> '#40a7e3',		'desc' => ' history compose area text');
$arr_en[]=array( 'name' => 'historyComposeAreaFgService',		'color'=> '#40a7e3',		'desc' => ' history compose area text when replying to a media message');
$arr_en[]=array( 'name' => 'historyComposeIconFg',		'color'=> '#40a7e3',		'desc' => ' history compose area icon (like emoji, attach, bot command..)');
$arr_en[]=array( 'name' => 'historyComposeIconFgOver',		'color'=> '#40a7e3',		'desc' => ' history compose area icon with mouse over');
$arr_en[]=array( 'name' => 'historySendIconFg',		'color'=> '#40a7e3',		'desc' => ' send message icon');
$arr_en[]=array( 'name' => 'historySendIconFgOver',		'color'=> '#40a7e3',		'desc' => ' send message icon with mouse over');
$arr_en[]=array( 'name' => 'historyPinnedBg',		'color'=> '#40a7e3',		'desc' => ' pinned message area background');
$arr_en[]=array( 'name' => 'historyReplyBg',		'color'=> '#40a7e3',		'desc' => ' reply / forward / edit message area background');
$arr_en[]=array( 'name' => 'historyReplyIconFg',		'color'=> '#40a7e3',		'desc' => ' reply / forward / edit message left icon');
$arr_en[]=array( 'name' => 'historyReplyCancelFg',		'color'=> '#40a7e3',		'desc' => ' reply / forward / edit message cancel button');
$arr_en[]=array( 'name' => 'historyReplyCancelFgOver',		'color'=> '#40a7e3',		'desc' => ' reply / forward / edit message cancel button with mouse over');
$arr_en[]=array( 'name' => 'historyComposeButtonBg',		'color'=> '#40a7e3',		'desc' => ' unblock / join channel / mute channel button background');
$arr_en[]=array( 'name' => 'historyComposeButtonBgOver',		'color'=> '#40a7e3',		'desc' => ' unblock / join channel / mute channel button background with mouse over');
$arr_en[]=array( 'name' => 'historyComposeButtonBgRipple',		'color'=> '#40a7e3',		'desc' => ' unblock / join channel / mute channel button ripple effect');
$arr_en[]=array( 'name' => 'overviewCheckBg',		'color'=> '#00000040',		'desc' => ' shared files / links checkbox background for not selected rows when some rows are selected');
$arr_en[]=array( 'name' => 'overviewCheckFg',		'color'=> '#40a7e3',		'desc' => ' shared files / links checkbox icon for not selected rows when some rows are selected');
$arr_en[]=array( 'name' => 'overviewCheckFgActive',		'color'=> '#40a7e3',		'desc' => ' shared files / links checkbox icon for selected rows');
$arr_en[]=array( 'name' => 'overviewPhotoSelectOverlay',		'color'=> '#40ace333',		'desc' => ' shared photos / videos / links fill for selected rows');
$arr_en[]=array( 'name' => 'profileStatusFgOver',		'color'=> '#7c99b2',		'desc' => ' group members list in group profile user last seen text with mouse over');
$arr_en[]=array( 'name' => 'profileVerifiedCheckBg',		'color'=> '#40a7e3',		'desc' => ' profile verified check icon background');
$arr_en[]=array( 'name' => 'profileVerifiedCheckFg',		'color'=> '#40a7e3',		'desc' => ' profile verified check icon tick');
$arr_en[]=array( 'name' => 'profileAdminStartFg',		'color'=> '#40a7e3',		'desc' => ' group members list admin star icon');
$arr_en[]=array( 'name' => 'notificationsBoxMonitorFg',		'color'=> '#40a7e3',		'desc' => ' custom notifications settings box monitor color');
$arr_en[]=array( 'name' => 'notificationsBoxScreenBg',		'color'=> '#40a7e3',		'desc' => ' #6389a8',		'desc' => ' custom notifications settings box monitor screen background');
$arr_en[]=array( 'name' => 'notificationSampleUserpicFg',		'color'=> '#40a7e3',		'desc' => ' custom notifications settings box small sample userpic placeholder');
$arr_en[]=array( 'name' => 'notificationSampleCloseFg',		'color'=> '#d7d7d7',		'desc' => ' custom notifications settings box small sample close button placeholder');
$arr_en[]=array( 'name' => 'notificationSampleTextFg',		'color'=> '#d7d7d7',		'desc' => ' custom notifications settings box small sample text placeholder');
$arr_en[]=array( 'name' => 'notificationSampleNameFg',		'color'=> '#939393',		'desc' => ' custom notifications settings box small sample name placeholder');
$arr_en[]=array( 'name' => 'mainMenuBg',		'color'=> '#40a7e3',		'desc' => ' main menu background');
$arr_en[]=array( 'name' => 'mainMenuCoverBg',		'color'=> '#40a7e3',		'desc' => ' main menu top cover background');
$arr_en[]=array( 'name' => 'mainMenuCoverFg',		'color'=> '#40a7e3',		'desc' => ' main menu top cover text');
$arr_en[]=array( 'name' => 'mediaPlayerBg',		'color'=> '#40a7e3',		'desc' => ' audio file player background');
$arr_en[]=array( 'name' => 'mediaPlayerActiveFg',		'color'=> '#40a7e3',		'desc' => ' audio file player playback progress already played part');
$arr_en[]=array( 'name' => 'mediaPlayerInactiveFg',		'color'=> '#40a7e3',		'desc' => ' audio file player playback progress upcoming (not played yet) part with mouse over');
$arr_en[]=array( 'name' => 'mediaPlayerDisabledFg',		'color'=> '#9dd1ef',		'desc' => ' audio file player loading progress (when you\'re playing an audio file and switch to the previous one which is not loaded yet)');
$arr_en[]=array( 'name' => 'mediaviewFileBg',		'color'=> '#40a7e3',		'desc' => ' file rectangle background (when you view a png file in Media Viewer and go to a previous, not loaded yet, file)');
$arr_en[]=array( 'name' => 'mediaviewFileNameFg',		'color'=> '#40a7e3',		'desc' => ' file name in file rectangle');
$arr_en[]=array( 'name' => 'mediaviewFileSizeFg',		'color'=> '#40a7e3',		'desc' => ' file size text in file rectangle');
$arr_en[]=array( 'name' => 'mediaviewFileRedCornerFg',		'color'=> '#d55959',		'desc' => ' red file thumbnail placeholder corner in file rectangle (for a file without thumbnail, like .pdf)');
$arr_en[]=array( 'name' => 'mediaviewFileYellowCornerFg',		'color'=> '#e8a659',		'desc' => ' yellow file thumbnail placeholder corner in file rectangle (for a file without thumbnail, like .zip)');
$arr_en[]=array( 'name' => 'mediaviewFileGreenCornerFg',		'color'=> '#49a957',		'desc' => ' green file thumbnail placeholder corner in file rectangle (for a file without thumbnail, like .exe)');
$arr_en[]=array( 'name' => 'mediaviewFileBlueCornerFg',		'color'=> '#599dcf',		'desc' => ' blue file thumbnail placeholder corner in file rectangle (for a file without thumbnail, like .dmg)');
$arr_en[]=array( 'name' => 'mediaviewFileExtFg',		'color'=> '#40a7e3',		'desc' => ' file extension text in file thumbnail placeholder in file rectangle');
$arr_en[]=array( 'name' => 'mediaviewMenuBg',		'color'=> '#383838',		'desc' => ' context menu in Media Viewer background');
$arr_en[]=array( 'name' => 'mediaviewMenuBgOver',		'color'=> '#505050',		'desc' => ' context menu item background with mouse over');
$arr_en[]=array( 'name' => 'mediaviewMenuBgRipple',		'color'=> '#676767',		'desc' => ' context menu item ripple effect');
$arr_en[]=array( 'name' => 'mediaviewMenuFg',		'color'=> '#40a7e3',		'desc' => ' context menu item text');
$arr_en[]=array( 'name' => 'mediaviewBg',		'color'=> '#222222eb',		'desc' => ' Media Viewer background');
$arr_en[]=array( 'name' => 'mediaviewVideoBg',		'color'=> '#40a7e3',		'desc' => ' Media Viewer background when viewing a video in full screen');
$arr_en[]=array( 'name' => 'mediaviewControlBg',		'color'=> '#0000003c',		'desc' => ' controls background (like next photo / previous photo)');
$arr_en[]=array( 'name' => 'mediaviewControlFg',		'color'=> '#40a7e3',		'desc' => ' controls icon (like next photo / previous photo)');
$arr_en[]=array( 'name' => 'mediaviewCaptionBg',		'color'=> '#11111180',		'desc' => ' caption text background (when viewing photo with caption)');
$arr_en[]=array( 'name' => 'mediaviewCaptionFg',		'color'=> '#40a7e3',		'desc' => ' caption text');
$arr_en[]=array( 'name' => 'mediaviewTextLinkFg',		'color'=> '#91d9ff',		'desc' => ' caption text link');
$arr_en[]=array( 'name' => 'mediaviewSaveMsgBg',		'color'=> '#40a7e3',		'desc' => ' save to file toast message background in Media Viewer');
$arr_en[]=array( 'name' => 'mediaviewSaveMsgFg',		'color'=> '#40a7e3',		'desc' => ' save to file toast message text');
$arr_en[]=array( 'name' => 'mediaviewPlaybackActive',		'color'=> '#c7c7c7',		'desc' => ' video playback progress already played part');
$arr_en[]=array( 'name' => 'mediaviewPlaybackInactive',		'color'=> '#252525',		'desc' => ' video playback progress upcoming (not played yet) part');
$arr_en[]=array( 'name' => 'mediaviewPlaybackActiveOver',		'color'=> '#ffffff',		'desc' => ' video playback progress already played part with mouse over');
$arr_en[]=array( 'name' => 'mediaviewPlaybackInactiveOver',		'color'=> '#474747',		'desc' => ' video playback progress upcoming (not played yet) part with mouse over');
$arr_en[]=array( 'name' => 'mediaviewPlaybackProgressFg',		'color'=> '#ffffffc7',		'desc' => ' video playback progress text');
$arr_en[]=array( 'name' => 'mediaviewPlaybackIconFg',		'color'=> '#40a7e3',		'desc' => ' video playback controls icon');
$arr_en[]=array( 'name' => 'mediaviewPlaybackIconFgOver',		'color'=> '#40a7e3',		'desc' => ' video playback controls icon with mouse over');
$arr_en[]=array( 'name' => 'mediaviewTransparentBg',		'color'=> '#ffffff',		'desc' => ' transparent filling part (when viewing a transparent .png file in Media Viewer)');
$arr_en[]=array( 'name' => 'mediaviewTransparentFg',		'color'=> '#cccccc',		'desc' => ' another transparent filling part');
$arr_en[]=array( 'name' => 'notificationBg',		'color'=> '#40a7e3',		'desc' => ' custom notification window background');
?>
